### ISSUE TITLE
Support for JS snippets

### ISSUE THREAD

**Issue by cecton** [rustminded/xtask-wasm#10]
Related to https://github.com/IMI-eRnD-Be/wasm-run/issues/68#issue-936469161

**Comment by Geens** [comment]
I just noticed this too. wasm_bindgen_cli_support::Output has an emit() method which writes out all outputs. I've replaced output writing in Dist::run() and this seems to work for me. I'll create a pull request with my solution

**Comment by cecton** [comment]
Thank you I will check on monday

**Comment by cecton** [comment]
I released the 0.2.0 version with your fix.

**Comment by cecton** [comment]
Sorry I'm gonna yield it. I need to include the latest xtask-watch upgrade.

**Comment by cecton** [comment]
Released in 0.2.1 (or 0.2.2 I forgot)

**Comment by Geens** [comment]
I just tested it and everything works. Thanks a lot!
